seas-computing/mark-one

.travis.yml
.travis_version_bump.sh
package-lock.json
package.json

This tweaks the process set up in #35 by removing the automatic deployment of the master branch at a new minor version, and changes the develop branch to deploy as a prerelease version (tagged as `-release`) instead of a patch version. 
Since we're removing the automation on the master branch and thus leaving out a lot of the conditional checks, I think we can also safely combine the version bump and npm publish into a single stage.

Only automate publishing the develop branch to npm

---

src/Buttons/BorderlessButton.tsx
src/Buttons/Button.tsx
src/Buttons/__tests__/BorderlessButton.test.tsx
src/Buttons/__tests__/Button.test.tsx

Instead of importing `VARIANT` enum directly from the `Theme` path, update the path to be relative to solve course-planner import error in which the `Button` and `BorderlessButton` components could not be found.
to change)

Update VARIANT import to have relative paths

---

src/Layout/Header.tsx

Header drop-shadow was making it difficult to integrate header tabs into the rest of the page. As discussed in a sprint planning meeting, this should be removed
Before:  
After:

Remove drop-shadow from header

---

examples/Tables/Table.md
src/Layout/PageBody.tsx
src/Tables/Table.tsx
src/Tables/TableCell.tsx
src/Tables/__tests__/Table.test.tsx
src/Tables/index.ts

This PR removes the margin around the `Table` component, since the margin was causing a horizontal scrollbar to appear in Course Planning. The margin was moved to the `PageBody` component instead. Also, the prop `alignment` was added to the `TableCell` component so that users can adjust how the content within the `td` is positioned (`text-align` is set to `left`, `right`, or `center`). The default value of the `alignment` prop is `left`.
to change)

Table & TableCell Components: Remove Table margin and add TableCell alignment prop

---

src/Theme/MarkOneTheme.ts

This PR addresses this error in the `Course Planning` app: 
Individual areas cannot be accessed without casting using `ColorRange`, which was a broader type than required. Instead of `ColorRange` as a type, I set the type for `area` to `{ [key: string]: string };`
to change)

Fix Typing for TableCell backgroundColor prop

---

src/Theme/MarkOneTheme.ts

The `backgroundColor` was not mapped correctly for `mat & me.` The course prefix `mat & me` was missing as a course prefix in the `area` object. Originally, it was listed as `matme` in the `area` object.
to change)

Add missing course prefix

---

src/Layout/Header.tsx

A small tweak to the `Header` component to make it work better with `PageTitle` by re-aligning child components using `align-items: baseline;`. This, in turn means that things are vertically center aligned, rather than aligned to the bottom of the header.
Before:  
After:

Adjust Header component to work better with PageTitle

---

examples/Modals/Modal.md
examples/Modals/ModalFooter.md
src/Modals/ModalFooter.tsx
src/Modals/index.ts

Adds a Modal Footer component to the library, and integrates it into the Examples for the modal. Since the `ModalFooter` is just a `styled-component` wrapped in `withTheme`, I haven't added any tests for the component -- any tests would just be verifying that third-party libraries do what they're supposed to, and I don't think that's necessary for our needs. Happy to discuss further if you feel differently.

Modal Footer

---

examples/Headings/SectionHeading.md
examples/Modals/Modal.md
examples/Modals/ModalFooter.md
examples/Modals/ModalHeader.md
package-lock.json
package.json
src/Headings/SectionHeading.tsx
src/Headings/index.ts
src/Modals/ModalFooter.tsx
src/Modals/ModalHeader.tsx
src/Modals/__tests__/ModalHeader.test.tsx
src/Modals/index.ts

Adds a `<ModalHeader>` component as a follow on to #53 and #54. Adds a top bar to the modal, and renders any `children` as title text and, optionally, adds a close button to the top-right corner.
This PR did start to sprawl a little bit, as I added a generic `<SectionHeading>` component, which I've extended and modified for use within the `<ModalHeader>`. I also had to address some weird styleguidist behaviors by upgrading the library to [the newest version][v11], which improves support for typescript and changes the default behavior to prefer default exports over named ones.
[v11]: https://github.com/styleguidist/react-styleguidist/releases/tag/v11.0.0

Modal Header

---

src/Modals/ModalBody.tsx
src/Modals/ModalHeader.tsx

Something weird happened with my auto-importing and those modules were loaded from the non-relative paths. I'm not sure why it did that and honestly I'm a little surprised it even worked in the mark-one stuff. I'll need to look into that and potentially see if that's something that CI could catch for us.
fixes seas-computing/course-planner#191

Change import paths to be relative

---

examples/Tables/Table.md
src/Tables/Table.tsx
src/Tables/TableBody.tsx
src/Tables/TableCell.tsx
src/Tables/TableHead.tsx
src/Tables/TableHeadingCell.tsx
src/Tables/TableHeadingSpacer.tsx
src/Tables/TableRow.tsx
src/Tables/TableRowHeadingCell.tsx
src/Tables/__tests__/Table.test.tsx
src/Tables/index.ts
styleguide.config.js

This PR is making a number of tweaks to our table components to accommodate the beast that is the Course Instance table. It adds two new components (a `HeadingSpacer` and `RowHeader`), updates some of the typings to allow for `col` and `colgroup` elements and multiple `TableRow` elements inside a header, and makes some general styling tweaks to get us as close as possible to Vittorio's prototype. I believe I've managed to do this while maintaining full backwards-compatibility, so there shouldn't be any breaking changes in the other course-planner tables that already exist.

Update table components

---

src/Tables/Table.tsx
src/Tables/TableBody.tsx
src/Tables/TableCell.tsx
src/Tables/TableHead.tsx
src/Tables/TableHeadingCell.tsx
src/Tables/TableRow.tsx
src/Tables/TableRowHeadingCell.tsx

I made a mistake in #59, leaving in imports from 'Theme' that should have been '../Theme'. I'm also changing the type for `rowSpan` and `colSpan` from `number` to `string`, since that's closer to how regular html would be written. 
With `number` the usage would have to be:
```tsx
<TableHeadingCell colSpan={2}>Heading</TableHeadingCell>
```
While with `string` the usage would be:
```tsx
<TableHeadingCell colSpan="2">Heading</TableHeadingCell>
```

Update Table Components (Revision)

---

examples/Headings/SectionHeading.md
examples/Tables/Table.md
src/Tables/TableCellList.tsx
src/Tables/TableCellListItem.tsx
src/Tables/index.ts

The current course-planner prototypes frequently use lists inside of a TableCell. I think it makes sense to have this as a special, Table specific design (as opposed to a more generalized List design), since this will probably be a pattern we employ in other circumstances.
This is needed for the work in seas-computing/course-planner#196

TableCellList components

---

src/Tables/TableCell.tsx
src/Tables/TableRowHeadingCell.tsx
src/Tables/index.ts

This will allow us to vertically align the text inside of the TableCell and TableRowHeadingCell components, as discussed during the spring review session from 05/22. 
This was meant to include f49de4469ffd1566a677600fcdecdcc3413e5584, but I accidentally pushed that up to `develop` instead of the feature branch.

Add verticalAlignment prop to TableCells

---

examples/Dropdown/Dropdown.md
src/Dropdown/Dropdown.tsx
src/Dropdown/__tests__/Dropdown.test.tsx
src/Forms/index.ts

The id property is needed to associate the label of the dropdown with the dropdown itself. I've added the id property to component in component definition, test component, and markdown example.
to change)
Addresses [#214](https://github.com/seas-computing/course-planner/issues/214)

Add 'id' property to Dropdown component

---

src/Buttons/BorderlessButton.tsx
src/Buttons/Button.tsx

Previously, `id` was specified as a property for both Button and BorderlessButton components, but the `id` property was not actually passed down to the components. This PR passes the `id` down to the component.
to change)
Addresses [#214](https://github.com/seas-computing/course-planner/issues/214)

Pass id property to Button and BorderlessButton components

---

examples/Forms/Dropdown.md
examples/Forms/TextInput.md
src/Forms/Dropdown.tsx
src/Forms/TextInput.tsx
src/Forms/__tests__/Dropdown.test.tsx
src/Forms/__tests__/TextInput.test.tsx

This pull request adds an optional `forwardRef` prop to the `TextInput` and `Dropdown` components. This will allow us to shift the focus to these components, and this change was motivated by making our `Course Planning` modals more accessible. Examples of doing this are included in the `TextInput` and `Dropdown` markdown files.
to change)
Addresses [#235](https://github.com/seas-computing/course-planner/issues/235)

TextInput & Dropdown: Add forwardRef prop to add ability to shift focus to these components

---

src/Forms/Dropdown.tsx
src/Forms/Label.tsx
src/Forms/TextInput.tsx
src/Forms/ValidationErrorMessage.tsx
src/Forms/__tests__/TextInput.test.tsx
src/Icons/IconLink.tsx
src/Layout/PageBody.tsx
src/Links/Link.tsx
src/Spinners/LoadSpinner.tsx
src/Spinners/LoadSpinnerText.tsx
src/Tables/TableBody.tsx
src/Tables/TableCell.tsx
src/Tables/TableCellListItem.tsx
src/Tables/TableHead.tsx
src/Tables/TableHeadingCell.tsx
src/Tables/TableRowHeadingCell.tsx
src/Tabs/TabList.tsx
src/Tabs/TabListItem.tsx

The absolute import for Theme doesn't work when the package is installed in an app. This has been happening when my editor auto-imports packages, so I'll need to fix that, or explore how we can add some kind of check for this.
Apologies for the inconvenience.

Fix absolute paths

---

examples/Modals/ModalHeader.md
src/Modals/Modal.tsx
src/Modals/ModalHeader.tsx
src/Modals/__tests__/Modal.test.tsx

This pull request adds an optional `forwardRef` prop to the `Modal` and `ModalHeader`. The props specifies the ref of the modal, which is used to direct the focus. When the user clicks on the button to open the Modal, the focus should shift to the modal's header for accessibility purposes. This PR adds logic to redirect the focus to the first focusable element in the modal when the modal is visible, and it also traps the focus in the modal when the modal is visible.
to change)
Addresses [#235](https://github.com/seas-computing/course-planner/issues/235)

Modal and ModalHeader components - Trap Focus in Modal when Modal is Visible

---

src/Theme/ThemeTypes.ts
src/Theme/utils.ts
src/styled.d.ts

The existing method of declaring all the theme types as part of the styled-components namespace was breaking when the library was published, since none of those themes were being exported and thus were missing when Theme/utils.ts tried to import them. This moves those sub-levels into the ThemeTypes.ts file (which will be compiled/exported), then declares the ValidThemeValues as part of the utils module itself.
As a quick and dirty way to test the compiled mark-one with course planner:
In local version of mark-one:
1. Remove any existing lib directory: `rm -rf ./lib`
2. compile the code: `npm run prepublishOnly`
In course-planner:
1. run `npm install` 
2. remove the existing lib directory from the installed version of mark-one: `rm -rf node_modules/mark-one/lib`
3. copy the built version …

Split sublevel theme types into new file

---

src/Forms/Fieldset.tsx

This PR updates the path of the `NoteText` import for the `Fieldset` component to be a relative path. Absolute paths do not work with the integration of Mark-One to Course Planner. Absolute paths only work in the context of the local TypeScript project itself.
to change)
Addresses [#229](https://github.com/seas-computing/course-planner/issues/229)

Update path from absolute to relative path

---

examples/Modals/ModalBody.md
src/Modals/ModalBody.tsx

This PR adds the CSS property `overflow` to the `ModalBody` so that if the modal contents are larger than the modal itself, the user will be able to scroll through the contents. I added the CSS property to the body instead of the overall modal component so that the title of the modal would be 'sticky' and could always be seen.
to change)
Addresses [#235](https://github.com/seas-computing/course-planner/issues/235)

Solve for Modal Content Overflow

---

examples/Links/ExternalLink.md
src/Links/ExternalLink.tsx
src/Links/index.ts

Our existing Link component is a wrapper around ReactRouter's Link, so we can only use it for navigation within the app. This ExternalLink is just a `styled.a` with CSS to match the Link, so that we can create links to external pages that look similar.
The specific use case for this is the "log out" link from #246

Create ExternalLink component

---

examples/Forms/CheckLabel.md
examples/Forms/Checkbox.md
examples/Forms/Dropdown.md
examples/Forms/Fieldset.md
examples/Forms/InputLabel.md
examples/Forms/RadioButton.md
examples/Forms/TextInput.md
examples/Modals/ModalBody.md
src/Forms/CheckLabel.tsx
src/Forms/Checkbox.tsx
src/Forms/Dropdown.tsx
src/Forms/Fieldset.tsx
src/Forms/InputLabel.tsx
src/Forms/Label.tsx
src/Forms/RadioButton.tsx
src/Forms/TextInput.tsx
src/Forms/__tests__/Checkbox.test.tsx
src/Forms/__tests__/Dropdown.test.tsx
src/Forms/__tests__/RadioButton.test.tsx
src/Forms/index.ts

The purpose of this PR is to fix the formatting for the `RadioButton` and `Checkbox` components so that when they are used in a form in conjunction with the `TextInput` component, they are all appropriately aligned at the same start point. With the previous state of these components, this is how the components look when used together:
I added `TextInput` and `RadioButton` components to the `ModalBody` overflow example to demonstrate the alignment of the components with the updated code:
to change)
Addresses [#229](https://github.com/seas-computing/course-planner/issues/229)

Update formatting for RadioButton and Checkbox components

---

examples/Buttons/BorderlessButton.md
examples/Buttons/Button.md
src/Buttons/BorderlessButton.tsx
src/Buttons/Button.tsx
src/Buttons/__tests__/BorderlessButton.test.tsx
src/Buttons/__tests__/Button.test.tsx
src/Theme/MarkOneWrapper.tsx

This interface was added as a result of feedback from the course planner [absence modal PR ](https://github.com/seas-computing/course-planner/pull/276). In that ticket, I was using `document.getElementById` to get a reference to button elements to focus them. Jonathan Seitz recommended that we should be using `ref` instead. We had a discussion on this and concluded that since the properties `ref` and `aria-label` will eventually be used across many different `mark one` components, it would make sense to make an interface for these components at the top level of `mark one` so that component props could extend the interface to include these common props. We decided it made sense to only implement the interface for the components needed in the absence modal for now, which would be the button …

Add Mark One Props Interface

---

examples/Forms/Dropdown.md
examples/Forms/TextInput.md
src/Forms/Dropdown.tsx
src/Forms/TextInput.tsx
src/Forms/__tests__/Dropdown.test.tsx
src/Forms/__tests__/TextInput.test.tsx

In the Course Planner Course Admin modal, we would like to have the "Select an existing area" dropdown to be disabled when the user is interacting with the "Create New Area" text input field, so I've exposed the `disabled` property on the `Dropdown` component. Also, it was noted in our retrospective that it would be nice to have the radio button selected when one of the elements were clicked (e.g. have the Create New Area radio button selected when the text input field is clicked), so I also included an optional `onClick` property for the `TextInput` and `Dropdown.`
to change)
Addresses [#272](https://github.com/seas-computing/course-planner/issues/272)

Add disabled property to Dropdown and onClick property to Dropdown & TextInput

---

src/Buttons/BorderlessButton.tsx
src/Buttons/Button.tsx
src/Theme/index.ts

After loading the new `mark one` version in Course Planner, I was not able to access the `forwardRef` prop in `BorderlessButton`. After discussing with J Seitz, we found that the issue was with the import statements. The paths in the `Button` components for the MarkOneProps interface must be relative, and absolute paths break when you use the library in another project.
to change)
Addresses [#252](https://github.com/seas-computing/course-planner/issues/252)

Bug Fix: Update paths in Button components to be relative instead of absolute

---

src/Forms/Checkbox.tsx
src/Forms/Dropdown.tsx
src/Forms/RadioButton.tsx
src/Forms/TextInput.tsx

We decided to take advantage of the HTML `required` property to indicate required form fields in the course admin modal. This property had not been exposed previously. I assigned the value of `isRequired` to the `required` property of the `TextInput` and `Dropdown` components.
to change)
Addresses [#229](https://github.com/seas-computing/course-planner/issues/229)

Add "required" property for TextInput and Dropdown

---

src/Forms/Fieldset.tsx

I was having issues with bringing up the Course Planner app with the latest code in `develop.` This is the error that I was getting:
The issue appears to be that we were not using a relative path when importing `fromTheme` in `Fieldset.` `Fieldset` was updated to import `fromTheme` from `../Theme` instead of `Theme`.
to change)
Fixes #274

Update import statement of fromTheme to use a relative path

---

examples/Tables/Table.md
src/Forms/__tests__/RadioButton.test.tsx
src/Tables/TableCell.tsx
src/Tables/__tests__/Table.test.tsx
src/Theme/MarkOneTheme.ts
src/Theme/ThemeTypes.ts
src/Theme/utils.ts

This PR adds text styling to the contents within a table cell. The `medium` and `negative` `text` colors in the theme were updated per accessibility (color contrast) recommendations from Vittorio in ticket [#300](https://github.com/seas-computing/course-planner/issues/300). I added an optional `variant` property to the `TableCell` so that users can use the `VARIANT.MEDIUM` (which we will use for "No Longer Active" faculty absence fields in Course Planner) styling and `VARIANT.NEGATIVE` (which we will use for other faculty absences that need attention in Course Planner) styling. If the user does not specify a variant, the text `font-weight` and `color` will default to the theme's `base` color and `medium` weight, which is how all table cells were styled originally before this ticket.
to …

TableCell Text Styling

---

src/Tables/TableCell.tsx
src/Tables/TableRowHeadingCell.tsx

This PR removes the font-family property from the `TableCell` and `TableRowHeadingCell` components. The font-family will instead be inherited from the components' parents. This way, the font of the table data in Course Planner should be sans-serif. 
to change)
Fixes [#386](https://github.com/seas-computing/course-planner/issues/386)

Remove font-family property from TableCell and TableRowHeadingCell

---

examples/Lists/List.md
src/Lists/List.tsx
src/Lists/ListItem.tsx
src/Lists/__tests__/List.test.tsx
src/Lists/index.ts
src/index.ts

These components are variations of the `TableCellList` and `TableCellListItem`, with an "ordered" prop added to the List component to switch between a `<ul>` and `<ol>` element. This doesn't affect the appearance of the list, but it still important semantically.
Additionally, the borders between the list children have been moved to the parent List element, which provides just a bit more flexibility if we ever want to create multiple list components.
to change)
Fixes seas-computing/course-planner#407

Create generic list components

---

src/Modals/ModalMessage.tsx
src/Theme/utils.ts
src/const.ts

In most cases, I would anticipate the `role` and `aria-live` values would be 'alert' and 'assertive, respectively. Since this may not always be the case, I added the props `role` and `ariaLive` so that the user can change the values but also added default values for both of these properties.
to change)
Fixes #374

Add 'role' and 'aria-live' properties to ModalMessage

---

src/Popover/Popover.tsx

Just having a max-width was causing weird issues when I tried to add
longer text into the body of the popover in Course Planner. The fastest
fix I found was to also set a width equal to max-content, which makes it
use as much space as it actually needs, up to that 10em max-width.
to change)

Size Popover to content

---

src/Forms/Combobox.tsx

Added button type to combo box dropdown. This prevents the button from accidentally submitting the form. You can see a reproduction of this by pasting the below code into the docs [here](https://seas-computing.github.io/mark-one/#/Forms?id=combobox)
to change)
Fixes #150

Set combo box button type

---

src/Buttons/Button.tsx

The type for `onClick` was updated to accommodate providing async functions as a value for `onClick`. This is an attempt to fix the linter error in Course Planner: 
```
"Promise-returning function provided to attribute where a void return was expected"
```
for the `onClick` value of the submit button in the modals.
to change)
Fixes #638

Update Button component's onClick property type

---

examples/Forms/Form.md
src/Buttons/Button.tsx
src/Forms/Form.tsx
src/Forms/__tests__/Form.test.tsx

This PR updates the `Form` component to fix the following error that we are receiving when trying to use it: 
```
Type '{ children: Element[]; id: string; label: string; submitHandler: () => void; }' is not assignable to type 'IntrinsicAttributes & FormProps'.
Property 'children' does not exist on type 'IntrinsicAttributes & FormProps'. 
```
We have seen this error in the past when trying to update Mark One to React 18. This was solved by explicitly passing down `children` as a prop.
The PR also updates the `Button` component to include an optional `type` property. If not specified, the `type` defaults to `button`. This way, we will be able to specify a `type` of `submit` so that we can more properly handle and associate forms with submit buttons.
to change)
Fixes …

Fix Form and Button components

---

examples/Layout/MenuFlex.md
examples/Layout/Paragraph.md
src/Forms/__tests__/Form.test.tsx
src/Layout/MenuFlex.tsx
src/Layout/Paragraph.tsx
src/Layout/index.ts

This PR adds the `MenuFlex` and `Paragraph` components from the apply.seas project. These are common layout elements that we anticipate will be used in many apps going forward. 
Unused imports were accidentally left in from the previous PR (https://github.com/seas-computing/mark-one/pull/173), and they were removed in commit [76d28df](https://github.com/seas-computing/mark-one/pull/174/commits/76d28df51f50cbfb0226c1554f1170408366c4ee).
to change)
Fixes #45

Add MenuFlex and Paragraph components

---

src/Modals/ModalBody.tsx
src/Modals/ModalFooter.tsx

`PropsWithChildren` was included within the definition of the types for the `ModalBody` and `ModalFooter`. These changes are in response to getting a type error message when trying to use these components in the Makerspace project related to the `children` prop.
```
Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & ExecutionProps & RefAttributes<IStyledComponent<"web", Substitute<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, { ...; }>>>'.ts(2559)
```
to change)
- [ x] I have added JSDoc for all of my code (where applicable)
Fixes [#44](https://github.huit.harvard.edu/SEAS/makerspace/issues/44)

Fix Modal Body and Modal Footer components

---

examples/Typography/SectionSubHeading.md
src/Theme/MarkOneTheme.ts
src/Theme/ThemeTypes.ts
src/Typography/SectionSubHeading.tsx
src/Typography/index.ts

This PR adds a `SectionSubHeading` component representing an h3 element. In keeping with best practices in hierarchical headings, it should only be used under a SectionHeading (i.e. h2) to break up a section of text further.
Stylistically, it is bolder than the normal text and the `SectionHeading`, and between the two in size. It also has a larger `margin-top` than `margin-bottom` to separate it from surrounding text.
to change)
#184

Add SectionSubHeading Component

---

examples/Layout/Callout.md
src/Layout/Callout.tsx
src/Layout/index.ts
src/Theme/MarkOneTheme.ts
src/Theme/ThemeTypes.ts

This PR adds a `Callout` component, which is intended to display a piece of text that should stand out to the user. It is styled on a `<p>` element, the text size is larger than the standard type, and it has extra margins to separate it from the rest of the text.
You can pass a variant property from the `VARIANT` enum to set the background color. For accessibility purposes, only the `light` option from each variant's `ColorRange` is used, and the text color will always be `dark`. Additionally, the `role` property can be set to define the ARIA role of the callout, with a default value of 'note'.
to change)
Closes #185

Add Callout Component

---

examples/Layout/GridWrapper.md
src/Layout/GridWrapper.tsx
src/Layout/index.ts

This PR adds a `GridWrapper` component which serves as the top-level of the grid structure. It defines the 12-column grid, with space between rows and columns. It can be used to embed grids within other components, letting us define sub-grid arrangements when needed.
It provides default gap spacing and responsive gap spacing for small window sizes, both of which can be overridden by passing in a gap size using the `MarkOneTheme` `ws` values. The component does not apply any margins, padding, additional borders shadows, or other styling, which should be handled by parent/child components instead.
This PR also adds a GridWrapper markdown example, which will be replaced with a more thorough example using the `GridContainer` and `GridItem` components, once all three are complete.
to change) …

Add GridWrapper Component

---

examples/Spinners/LoadSpinner.md

This fixes the `ReferenceError: styled is not defined in the styleguide` in the second markdown example for the LoadSpinner by importing styled within the markdown example. It now properly displays the light color text on dark background example.
to change)
Fixes #199

Fix LoadSpinner Markdown Example Error

---

examples/Layout/GridContainer.md
examples/Layout/GridWrapper.md
src/Layout/GridContainer.tsx
src/Layout/__tests__/GridContainer.test.tsx
src/Layout/index.ts

This PR adds a GridContainer component, which is a low-level piece of the layout grid. It represents a sub-component of a larger grid, intended for use with multiple child components, and may itself contain another grid layout. It should be placed inside a `GridWrapper` and can contain `GridItem` components (the latter of which will be added in a future enhancement).
This PR also makes some slight changes to the `GridWrapper` markdown examples, in light of the `GridContainer` examples.
This PR also provides testing for the `getGridColumnStyles` function.
With the current implementation, users may experience some unexpected behavior in the display of the `GridContainer` when the total width of multiple adjacent `GridContainers` exceeds 12. Addressing this would overly complicate the code …

Add GridContainer Component
