seas-computing/mark-one

src/Theme/index.ts

Export VARIANT enum from Mark-One so that we can use it in the Course Planner course admin interface
to change)

Mark-One: Export VARIANT enum from MarkOneTheme

---

src/index.ts

This exports everything from the Links directory
to change)
Addresses [#163](https://github.com/seas-computing/course-planner/issues/163)

Export Links Directory

---

src/Forms/Label.tsx
src/Forms/TextInput.tsx

This adjusts the padding of the Text Input component so that there is left, top, and bottom padding within the input field per Vittorio's guidance. The vertical alignment was also adjusted so that the label text and input field text line up. 
to change)
Addresses [#175](https://github.com/seas-computing/course-planner/issues/175)

Text Input Component - Padding & Vertical Alignment Adjustments

---

examples/Modals/Modal.md
package-lock.json
package.json
src/Modals/Modal.tsx
src/Modals/__tests__/Modal.test.tsx
src/Modals/index.ts
src/index.ts

Implements a full-screen overlay modal, suitable for use with edit screens, confirmation dialogs, and other communication purposes.
The `ModalHeader` and `ModalFooter` components will come in separate PRs, and those will be responsible for more of the look and feel of the modals. This component is mostly handling the appearing and disappearing effects.

Create Modal component

---

examples/Modals/Modal.md
examples/Modals/ModalBody.md
examples/Modals/ModalFooter.md
examples/Modals/ModalHeader.md
src/Modals/ModalBody.tsx
src/Modals/index.ts

This is a very small helper component that just provides padding to make the content of a modal line up with the header and footer.

ModalBody Component

---

examples/Dropdown/Dropdown.md
examples/Modals/Modal.md
examples/Modals/ModalBody.md
examples/Modals/ModalFooter.md
examples/Modals/ModalHeader.md
src/Buttons/BorderlessButton.tsx
src/Buttons/Button.tsx
src/Dropdown/Dropdown.tsx
src/Dropdown/__tests__/Dropdown.test.tsx
src/Forms/TextInput.tsx
src/Modals/Modal.tsx
src/Modals/__tests__/Modal.test.tsx
src/Modals/__tests__/ModalHeader.test.tsx

This PR adds missing properties needed to create the Faculty Admin modal.
`Dropdown`: `disabled` and `required` properties were added for form validation purposes.
`TextInput`: `required` property was added for form validation purposes.
`Modal`: `aria-labelledBy` property was added for accessibility purposes.
to change)
Addresses [#214](https://github.com/seas-computing/course-planner/issues/214)

Dropdown, TextInput, and Modal Components - Add Missing Props Needed for Faculty Admin Modals

---

.github/workflows/04-documentation.yml

I had updated other references to the `docs/` directory from the existing workflow script, but did not update the filter-branch command to leave in the `styleguide/` directory.
to change)
Fixes #___

Correct subdirectory argument

---

.github/workflows/04-documentation.yml
package-lock.json
package.json

This will correct an issue with our documentation workflow so that the gh-pages code will be updated appropriately.
to change)
Fixes #___

Fix the documentation workflow

---

examples/Forms/Form.md
src/Forms/CheckLabel.tsx
src/Forms/Checkbox.tsx
src/Forms/Fieldset.tsx
src/Forms/Form.tsx
src/Forms/__tests__/Checkbox.test.tsx
src/Forms/__tests__/Fieldset.test.tsx
src/Forms/__tests__/Form.test.tsx
src/Forms/index.ts

This PR adds a `Form` component, which adds a margin to each of its direct children (e.g. In Course Planner, if we replace the Course Admin modal's form component using `<form>` with the `Form` component, each of the form field components will have a margin around them).
While discussing the form fields with Jonathan Seitz, we found that the checkbox in the course planner course admin modal is indented more compared to other form fields. This was because of the `padding-inline-start` property in `Fieldset,` so the value was updated depending on whether the border and legends are visible. 
Lastly, the `hideError` prop was integrated into the `Checkbox` component for formatting reasons in the same way it had been integrated with the `TextInput` and `Dropdown` components, so that the user …

Form Component and Updating Checkbox formatting

---

examples/Modals/ModalMessage.md
package-lock.json
package.json
src/Modals/ModalMessage.tsx
src/Modals/__tests__/ModalMessage.test.tsx
src/Modals/index.ts

This PR adds in the `ModalMessage` component, which will be used to display messages in the Course Planner modals. This component is a span that accepts an optional `id` property, `children` to display the text, and a `variant` as different message types are styled differently. The style variants match those of the `Button` component.
to change)
Fixes #373

Modal Message Component

---

examples/Buttons/ButtonDropdownMenu.md
examples/Forms/Form.md
examples/Modals/Modal.md
examples/Modals/ModalMessage.md
examples/Tables/Table.md
package-lock.json
package.json
src/Buttons/ButtonDropdownMenu.tsx
src/Buttons/ButtonDropdownMenuItem.tsx
src/Buttons/__tests__/ButtonDropdownMenu.test.tsx
src/Buttons/index.ts
src/Forms/CheckLabel.tsx
src/Forms/Checkbox.tsx
src/Forms/Fieldset.tsx
src/Forms/Form.tsx
src/Forms/__tests__/Checkbox.test.tsx
src/Forms/__tests__/Fieldset.test.tsx
src/Forms/__tests__/Form.test.tsx
src/Forms/__tests__/RadioButton.test.tsx
src/Forms/index.ts
src/Modals/ModalMessage.tsx
src/Modals/__tests__/ModalMessage.test.tsx
src/Modals/index.ts
src/Tables/TableCell.tsx
src/Tables/TableRowHeadingCell.tsx
src/Tables/__tests__/Table.test.tsx
src/Theme/MarkOneTheme.ts
src/Theme/utils.ts

This rolls up a number of minor changes made since v0.2.0, including:
Modal Message component for displaying success/failure messages inside modals (Closes seas-computing/course-planner#373)
Button Dropdown Menu (Closes seas-computing/course-planner#343)
Form Component (Closes seas-computing/course-planner#274)
Remove data font from Table components (Fixes seas-computing/course-planner#386)
Allow colored background in table cells (Fixes seas-computing/course-planner#300)

Release v0.3.0

---

examples/Forms/MultiLineTextInput.md
src/Forms/MultiLineTextInput.tsx
src/Forms/__tests__/MultiLineTextInput.test.tsx
src/Forms/index.ts

Implements a multi-line text input component (`textarea` under the hood) to fulfil https://github.com/seas-computing/course-planner/issues/452
to change)
Fixes https://github.com/seas-computing/course-planner/issues/452

Text area component

---

src/Lists/DropdownListItem.tsx

The padding of the `DropdownListItem` was causing issues in cases where we were using a `ButtonDropdownMenu` in Course Planner. The click event seemed to be triggered only intermittently. Each list item of the `ButtonDropdownMenu` contains a `ButtonDropdownMenuItem`, which each have padding. With the `DropdownListItem` component also having padding, if the user clicked on the `DropdownListItem`'s padding, the menu would collapse without triggering a click event on the `ButtonDropdownMenuItem`, causing confusion for the user. By removing the padding from the `DropListItem`, the user can click anywhere in the row of the menu list item to select the item.
to change)
Fixes [#515](https://github.com/seas-computing/course-planner/issues/515)

Remove padding from DropdownListItem component

---

examples/Buttons/Button.md
src/Buttons/Button.tsx

Hello Team,
this PR is related to the bug for #132 
I have added 'form' prop to the Button Component to bind that button with the specific form.
to change)
Fixes #132

added form prop to the button component

---

src/Forms/Dropdown.tsx
src/Forms/index.ts

This `DropdownOptionProps` interface is being exported so that it can be used in Course Planner.
to change)
Related to: [#532](https://github.com/seas-computing/course-planner/issues/532)

Export DropdownOptionProps interface

---

src/Modals/Modal.tsx
src/Modals/__tests__/Modal.test.tsx

This PR updates the `Modal` component such that the modal does not close when there is a `mouseDown` event on the modal and a `mouseUp` event on the modal backdrop. The `closeHandler` is only called when the `mouseDown` and `mouseUp` event both occur on the backdrop.
Previously, `event.stopPropagation` was being called when there was an `onClick` event on the modal. In the case where there was only a `mouseDown` on the modal, the propagation was not being stopped from bubbling up to the backdrop, so when the `mouseUp` event happened on the backdrop, it seems that it was as if a full click event happened on the backdrop.
to change)
Fixes [#538](https://github.com/seas-computing/course-planner/issues/538)

Bug fix: Modal Closing Behavior

---

src/Modals/Modal.tsx

While trying to test #137 in the course planner[1], I wound up seeing a few dozen test failures that seemed to be related to the closing behavior of the modal. It seems that there were two issues:
1. Removing the `evt.preventDefault()` call on the Modal itself was causing some click events to register on the backdrop, closing the modal before it should have.
2. Defining the `mouseDownOnModal` field in the render function was causing it to revert to `false` when the component re-rendered, preventing the modal from closing when it should have.
At least, I _think_ that's what was happening. I don't think either of those were really registering as issue when manually testing the browser, but I suspect something in the testing library click event handling was causing the unexpected behavior. …

Refactor fix for Modal background click behavior

---

src/Tabs/TabListItem.tsx
src/Tabs/__tests__/TabListItem.test.tsx

`aria-selected` is added to `TabListItemWrapper` on `TabListItem` file. The commit also tested and confirmed that the aria-selected is active and working as intended.
to change)
Fixes #[247](https://github.com/seas-computing/course-planner/issues/247)

Updated TabListItem component with aria-selected active feature.

---

examples/Alerts/GlobalMessage.md
examples/Buttons/Button.md
examples/Forms/MultiLineTextInput.md
examples/Hooks/useConfirm.md
examples/Modals/Modal.md
examples/Popover/Popover.md
package-lock.json
package.json
src/Alerts/GlobalMessage.tsx
src/Alerts/__tests__/GlobalMessage.test.tsx
src/Alerts/index.ts
src/Buttons/Button.tsx
src/Forms/Dropdown.tsx
src/Forms/MultiLineTextInput.tsx
src/Forms/__tests__/MultiLineTextInput.test.tsx
src/Forms/index.ts
src/Hooks/__tests__/useConfirm.test.tsx
src/Hooks/index.ts
src/Hooks/useConfirm.tsx
src/Lists/DropdownListItem.tsx
src/Modals/Modal.tsx
src/Modals/__tests__/Modal.test.tsx
src/Popover/Popover.tsx
src/Popover/index.ts
src/Tables/TableHeadingCell.tsx
src/Tables/TableRowHeadingCell.tsx
src/Tabs/TabListItem.tsx
src/Tabs/__tests__/TabListItem.test.tsx
src/index.ts

- Create `useConfirm` hook to warn about discarding unsaved changes (closes seas-computing/course-planner#419)
- Create `GlobalMessage` for top-level app notifications (closes seas-computing/course-planner#369)
- Create `TextArea` form component (closes seas-computing/course-planner#452)
- Create `Popover` component (closes seas-computing/course-planner#495)
- Clean up padding of DropdownListItem component (fixes seas-computing/course-planner#515)
- Add `form` prop to button component (Fixes #132 -- Thanks @sonusindhu)
- Export Props interface for `DropdownOptions` (fixes seas-computing/course-planner#532)
- Fix modal closing bug when clicking-and-dragging inside text fields (fixes seas-computing/course-planner#538)
- Remove node-canvas dependency to fix arm support in Course Planer (See …

Release v0.5.0

---

examples/Layout/Footer.md
src/Layout/Footer.tsx
src/Layout/__tests__/Footer.test.tsx
src/Layout/index.ts

This PR adds a `Footer` component, whose spacing matches the existing `Header` component. It accepts a `justify` and `background` prop, which control its horizontal spacing and background color. The contents of the Footer are rendered via the `children` prop.
to change)
Fixes #618

Footer Component

---

src/Layout/Footer.tsx
src/Layout/__tests__/Footer.test.tsx

This PR updates the `Footer` component so that its tag is corrected to `footer` as opposed to `main`.
to change)
Fixes #618

Fix Footer Tag

---

src/Forms/MultiLineTextInput.tsx

This removal of the `label` property is in response to the following test error in Course Planner: "TestingLibraryElementError: Found a label with the text of: Course Notes, however the element associated with this label (<textarea />) is non-labellable [https://html.spec.whatwg.org/multipage/forms.html#category-label]. If you really need to label a <textarea />, you can use aria-label or aria-labelledby instead."
The styled text area is already being labelled using the combination of the `htmlFor` property in the `InputLabel` component along with the `id` property in the `StyledTextArea` component.
to change)
Fixes [#638](https://github.huit.harvard.edu/SEAS/course-planner/issues/638)

Remove label property from StyledTextArea

---

src/Layout/PageBody.tsx

The purpose of adding a padding to `PageBody` is to solve for an issue in Course Planner in which the `Footer` covers the bottom of a table making the information in the table inaccessible to the user. By adding some padding to the bottom of `PageBody`, we are making it so that the footer does not obfuscate any information.
The purpose of adding a padding to PageBody is to solve for an issue in Course Planner in which the footer covers the bottom of a table making the information in the table inaccessible to the user. By adding some padding to the bottom of PageBody, we are making it so that the footer does not obfuscate any information.
to change)
Fixes #704

Fix PageBody

---

examples/Layout/Footer.md
src/Layout/Footer.tsx

This PR updates the CSS of the `Footer` component to account for unordered lists. Each of our apps will likely include a group of links in the `Footer', and this styling should be applied.
to change)
Fixes [#11](https://github.huit.harvard.edu/SEAS/react-boilerplate/issues/11)

Update Footer styling

---

examples/Forms/Form.md
src/Forms/Form.tsx
src/Forms/__tests__/Form.test.tsx

The submit handler also bakes in a call to `e.preventDefault()` to prevent the form default submission
This PR adds a submit handler to the form. This paves the way for (what is effectively) form submit actions to be moved out of button handlers, and into a dedicated submit handler on the form level where it belongs
to change)
Fixes #___

Add submit handler for form component

---

src/index.ts
src/styled.ts

It seems that the `DefaultTheme` override in the `styled.d.ts` file was causing problems in the build phase -- mainly that the declarations were not being carried over into the final output. To resolve, we're removing the `d.` from the filename, and exporting an empty module from the new file. Importing that empty module into our index barrel file seems to be enough to pick up the declarations and package them into the final output.
I tested this by running `npm run prepublishOnly` in the mark-one project root, which builds the code under `lib/`. I then copied that entire `lib` folder into the `node_modules/mark-one/` directory of a different project (i.e. `apply-seas-node`), removed the `styled.d.ts` from that project, and confirmed that typescript is still able to pick up the typing for …

Fix export of theme type

---

examples/Modals/Modal.md

Previously, the `Modal` Open/Close effects example's `TextInput` was not handling the input of text correctly, because the wrong attribute was being used in the `TextInput` component. Instead of `onChange`, it was trying to use `changeHandler` as the property name.
to change)
Fixes #167

Fix Modal Example

---

.github/workflows/01-test-suite.yml
.github/workflows/04-documentation.yml
.github/workflows/05-npm.yml
package-lock.json
package.json
src/Buttons/__tests__/BorderlessButton.test.tsx
src/Buttons/__tests__/Button.test.tsx

This updates React to version 18, which caused a need to update react-dom, @testing-library/react, and @fortawesome/react-fontawesome. We are updating the version to fix a conflicting dependency in the React Boilerplate repo in which it is expecting React 18.
to change)
Fixes [#25](https://github.huit.harvard.edu/SEAS/react-boilerplate/issues/25)

Update React to Version 18

---

examples/Typography/Stat.md
src/Typography/Stat.tsx
src/Typography/index.ts

This PR adds a `Stat` component which styles inline text representing data or statistics in a monospace font.
to change)
Closes #186

Add Stat Component

---

examples/Alerts/ToastNotification.md
src/Alerts/ToastNotification.tsx
src/Alerts/__tests__/ToastNotification.test.tsx
src/Alerts/index.ts

The `ToastNotification` component will be used to provide alerts for the user. The styling is based off of browser alerts. To get the notifications to stack vertically, this will require a separate wrapper container that will be implemented separately. 
to change)
Fixes #193

Toast Notification Component

---

examples/Alerts/ToastNotification.md
examples/Alerts/ToastNotificationWrapper.md
src/Alerts/ToastNotification.tsx
src/Alerts/ToastNotificationWrapper.tsx
src/Alerts/index.ts

The `ToastNotificationWrapper` component will be used to position the `ToastNotification` components such that they line up at the top right of the page.
The example includes a button to show the `ToastNotification` components wrapped in the `ToastNotificationWrapper` at the top right of the page. You will most likely need to scroll up to see the example, as it is purposely positioned outside of the regular example container. 
to change)
Fixes #197

Toast Notification Wrapper

---

examples/Layout/GridContainer.md

This PR makes a small change to remove mention of GridItem from the GridContainer markdown file.
to change)
Fixes #201

Remove Mention of GridItem
